[package]
name = "fs_objstore"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
clap = {version = "4.4.18", features= ["derive"]}
nanoid = "0.4.0"
nom = {version = "7.1.3", features = ["alloc"]}
nom_locate = "4.2.0"
